/* Generated By:JavaCC: Do not edit this line. Parser.java */
import java.util.ArrayList;
import exceptions.*;

/** ID lister. */
public class Parser implements ParserConstants {

  final public ASTNode Start() throws ParseException {
   ASTNode t;
    t = TopExp();
    jj_consume_token(EOL);
     {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode TopExp() throws ParseException {
        ASTNode t;
    t = AssignExp();
          {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode AssignExp() throws ParseException {
  ASTNode t1,t2;
    t1 = BoolExp();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(ASSIGN);
      t2 = BoolExp();
          t1 = new ASTAssign(t1,t2);
    }
           {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode BoolExp() throws ParseException {
   ASTNode t1, t2;
    t1 = DisjExp();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(AND);
      t2 = DisjExp();
           t1 = new ASTAnd(t1,t2);
    }
     {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode DisjExp() throws ParseException {
   ASTNode t1, t2;
    t1 = EqExp();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      jj_consume_token(OR);
      t2 = EqExp();
             t1 = new ASTOr(t1,t2);
    }
     {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode EqExp() throws ParseException {
   ASTNode t1, t2;
    t1 = Exp();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      jj_consume_token(EQ);
      t2 = Exp();
           t1 = new ASTEq(t1,t2);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
     {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Exp() throws ParseException {
  Token op;
  ASTNode t1, t2;
    t1 = Term();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        op = jj_consume_token(PLUS);
        break;
      case MINUS:
        op = jj_consume_token(MINUS);
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = Term();
                   if (op.kind == PLUS)
                         t1 = new ASTPlus(t1,t2);
                   else  t1 = new ASTSub(t1,t2);
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Term() throws ParseException {
  Token op;
  ASTNode t1, t2;
    t1 = Fact();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
      case DIV:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TIMES:
        op = jj_consume_token(TIMES);
        break;
      case DIV:
        op = jj_consume_token(DIV);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = Fact();
                   if (op.kind == TIMES)
                         t1 = new ASTMult(t1,t2);
                   else  t1 = new ASTDiv(t1,t2);
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Fact() throws ParseException {
  Token n;
  ASTNode t1;
  ASTNode t2=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITS:
      n = jj_consume_token(DIGITS);
                 t1 = new ASTNum(Integer.parseInt(n.image)); {if (true) return t1;}
      break;
    case LPAR:
      jj_consume_token(LPAR);
      t1 = TopExp();
      jj_consume_token(RPAR);
                               {if (true) return t1;}
      break;
    case VAR:
      jj_consume_token(VAR);
      jj_consume_token(LPAR);
      t1 = TopExp();
      jj_consume_token(RPAR);
                                          {if (true) return new ASTVar(t1);}
      break;
    case MINUS:
      jj_consume_token(MINUS);
      t1 = Fact();
                         {if (true) return new ASTNeg(t1);}
      break;
    case PLUS:
      jj_consume_token(PLUS);
      t1 = Fact();
                        {if (true) return t1;}
      break;
    case TRUE:
      n = jj_consume_token(TRUE);
              t1 = new ASTBoolean(true); {if (true) return t1;}
      break;
    case FALSE:
      n = jj_consume_token(FALSE);
               t1 = new ASTBoolean(false); {if (true) return t1;}
      break;
    case Id:
      n = jj_consume_token(Id);
              {if (true) return new ASTId(n.image);}
      break;
    case DEF:
      t1 = Def();
                {if (true) return t1;}
      break;
    case TIMES:
      jj_consume_token(TIMES);
      t1 = Fact();
                           {if (true) return new ASTDeRef(t1);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Def() throws ParseException {
        Token n;
        ASTNode t1, t2;
        ArrayList<Binding> binds = new ArrayList<Binding>();
    jj_consume_token(DEF);
    label_6:
    while (true) {
      n = jj_consume_token(Id);
      jj_consume_token(ASSOC);
      t1 = TopExp();
            binds.add(new Binding(n.image, t1));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Id:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
    }
    jj_consume_token(IN);
    t2 = TopExp();
    jj_consume_token(END);
            {if (true) return new ASTDef(binds, t2);}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[10];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x200000,0x40000,0x80000,0x400000,0x60,0x60,0x180,0x180,0x9322f0,0x800000,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[24];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 10; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 24; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  /** Main entry point. */
  /*public static void main(String args[]) {
    Parser parser = new Parser(System.in);
    ASTNode exp;

	Environment env = new Environment();
	
    while (true) {
	    try {
	      exp = parser.Start();
	      System.out.println("Syntax is okay: " + exp.eval(env) );
	    }
	    catch (Exception e) {
	      System.out.println ("Syntax Error!" + e.getMessage());
	      parser.ReInit(System.in);
	    }
    }
  }*/

}
