/* Generated By:JavaCC: Do not edit this line. EvaluatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EvaluatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Id = 5;
  /** RegularExpression Id. */
  int Num = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int TIMES = 9;
  /** RegularExpression Id. */
  int DIV = 10;
  /** RegularExpression Id. */
  int LPAR = 11;
  /** RegularExpression Id. */
  int RPAR = 12;
  /** RegularExpression Id. */
  int EL = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\":=\"",
  };

}
